In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of word',
    'your videos are good'
]

In [3]:
##Define the vocabulary size
voc_size=10000

##One Hot Representation
one_hot_rep=[one_hot(words,voc_size) for words in sent]


In [4]:
one_hot_rep

[[662, 4587, 7889, 640],
 [662, 4587, 7889, 5637],
 [662, 894, 7889, 4186],
 [1203, 3278, 3691, 4959, 1945],
 [1203, 3278, 3691, 4959, 854],
 [8904, 662, 626, 7889, 579],
 [4212, 9025, 1560, 4959]]

In [6]:
##word Embedding representattion
from tensorflow.keras.layers import Embedding 
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [9]:
sent_len=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0  662 4587 7889  640]
 [   0    0    0    0  662 4587 7889 5637]
 [   0    0    0    0  662  894 7889 4186]
 [   0    0    0 1203 3278 3691 4959 1945]
 [   0    0    0 1203 3278 3691 4959  854]
 [   0    0    0 8904  662  626 7889  579]
 [   0    0    0    0 4212 9025 1560 4959]]


In [10]:
##feature representation
dim=10

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 403ms/step


array([[[ 0.03360751, -0.02457613, -0.02921065,  0.04740336,
          0.0229617 ,  0.02445057,  0.00955665, -0.02129257,
         -0.01182063,  0.03154406],
        [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,
          0.0229617 ,  0.02445057,  0.00955665, -0.02129257,
         -0.01182063,  0.03154406],
        [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,
          0.0229617 ,  0.02445057,  0.00955665, -0.02129257,
         -0.01182063,  0.03154406],
        [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,
          0.0229617 ,  0.02445057,  0.00955665, -0.02129257,
         -0.01182063,  0.03154406],
        [-0.04056876,  0.04734216, -0.0023944 ,  0.03370135,
         -0.02567132, -0.01804418, -0.01662711,  0.0383641 ,
         -0.02556684, -0.03229078],
        [ 0.00880815, -0.04364449, -0.00098301,  0.00493062,
         -0.03379022, -0.03764179, -0.03391863,  0.00022797,
          0.00576439,  0.01424644],
        [ 0.03115717,  0.02467978,  0.03320587,  0.0

In [14]:
embedded_docs[0]

model.predict(embedded_docs[0])

1/1 [==============================] - 0s 115ms/step


array([[ 0.03360751, -0.02457613, -0.02921065,  0.04740336,  0.0229617 ,
         0.02445057,  0.00955665, -0.02129257, -0.01182063,  0.03154406],
       [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,  0.0229617 ,
         0.02445057,  0.00955665, -0.02129257, -0.01182063,  0.03154406],
       [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,  0.0229617 ,
         0.02445057,  0.00955665, -0.02129257, -0.01182063,  0.03154406],
       [ 0.03360751, -0.02457613, -0.02921065,  0.04740336,  0.0229617 ,
         0.02445057,  0.00955665, -0.02129257, -0.01182063,  0.03154406],
       [-0.04056876,  0.04734216, -0.0023944 ,  0.03370135, -0.02567132,
        -0.01804418, -0.01662711,  0.0383641 , -0.02556684, -0.03229078],
       [ 0.00880815, -0.04364449, -0.00098301,  0.00493062, -0.03379022,
        -0.03764179, -0.03391863,  0.00022797,  0.00576439,  0.01424644],
       [ 0.03115717,  0.02467978,  0.03320587,  0.02944303,  0.03992036,
         0.04190829, -0.00245134,  0.00995809